#!/bin/bash

scriptdir=`dirname $0`
cd $scriptdir

printWidth=20

testfiles=`ls tests.d/*.test`
tests=''
for f in $testfiles; do
    tst=`basename -s .test $f`
    tests="$tests $tst"
done

create-vol () {
    hdiutil create -megabytes 10 -fs 'Journaled HFS+' \
            -volname $1 -type SPARSE -attach ./$1.dmg
    sudo fsaclctl -p /Volumes/CopyFrom -e
}

create-all () {
    for t in $tests; do
        tnice=${t:2}
        printf "Creating: %${printWidth}s ..." "$tnice"
        if [ -d "$1/$t" ]; then
            bash test-runner tests.d/$t.test clean $1/$t || true
            rm -Rf "$1/$t" || true
        fi
        mkdir $1/$t
        bash test-runner tests.d/$t.test create $1/$t || echo FAIL
    done
}

clean-all () {
    for t in $tests; do
        tnice=${t:2}
        printf "Cleaning: %${printWidth}s ..." "$tnice"
        if [ -d "$1/$t" ]; then
            bash test-runner tests.d/$t.test clean $1/$t || true
            rm -Rf "$1/$t" || true
        fi
    done
}

verify-all () {
    for t in $tests; do
        tnice=${t:2}
        printf "Verifying: %${printWidth}s ..." "$tnice"
        bash test-runner tests.d/$t.test verify $2/$t $1/$t \
            && echo " ok" \
            || echo " FAIL"
    done
}

# Compare a single pair of files for all known properties.
compare-all () {
    for t in $tests; do
        tnice=${t:2}
        echo -n "Comparing: %${printWidth}s ..." "$tnice"
        bash test-runner tests.d/$t.test compare $1 $2 \
            && echo " ok" \
            || echo " FAIL"
    done
}

case $1 in
    create-all|create-vol|clean-all)
        $1 $2
    ;;
    verify-all|compare-all)
        $1 $2 $3
    ;;
    *)
        echo "Ops: "
        echo "   create-vol, create-all, verify-all, compare-all, clean-all"
        exit 1
    ;;
esac
