#!/bin/bash

scriptdir=`dirname $0`
cd $scriptdir

printWidth=20

testfiles=`ls tests.d/*.test`
tests=''
for f in $testfiles; do
    tst=`basename -s .test $f`
    tests="$tests $tst"
done

copyfiles=`ls copiers.d/*.cp`
copiers=''
for f in $copyfiles; do
    cpf=`basename -s .cp $f`
    copiers="$copiers $cpf"
done

create-vol () {
    hdiutil create -megabytes 10 -fs 'Journaled HFS+' \
            -volname $1 -type SPARSE -attach ./$1.dmg
    sudo fsaclctl -p /Volumes/CopyFrom -e
}

create-all () {
    for t in $tests; do
        tnice=${t:2}
        printf "Creating: %${printWidth}s ..." "$tnice"
        if [ -d "$1/$t" ]; then
            bash test-runner tests.d/$t.test clean $1/$t || true
            rm -Rf "$1/$t" || true
        fi
        mkdir $1/$t
        bash test-runner tests.d/$t.test create $1/$t \
            && echo " ok" \
            || echo " FAIL"
    done
}

clean-all () {
    for t in $tests; do
        tnice=${t:2}
        printf "Cleaning: %${printWidth}s\n" "$tnice"
        if [ -d "$1/$t" ]; then
            bash test-runner tests.d/$t.test clean $1/$t || true
            rm -Rf "$1/$t" || true
        fi
    done
}

verify-all () {
    for t in $tests; do
        tnice=${t:2}
        printf "Verifying: %${printWidth}s ..." "$tnice"
        bash test-runner tests.d/$t.test verify $2/$t $1/$t \
            && echo " ok" \
            || echo " FAIL"
    done
}

# Compare a single pair of files for all known properties.
compare-all () {
    for t in $tests; do
        tnice=${t:2}
        echo -n "Comparing: %${printWidth}s ..." "$tnice"
        bash test-runner tests.d/$t.test compare $1 $2 \
            && echo " ok" \
            || echo " FAIL"
    done
}

copy-all () {
    # Make sure there's no trailing /
    #echo "arg2 = $2"
    #echo "arg3 = $3"
    src="`dirname $1`/`basename $1`"
    dst="`dirname $2`/`basename $2`"
    echo "src = $src"
    echo "dst = $dst"
    for c in $copiers; do
        cnice=${c:3}
        printf "Copying with: %${printWidth}s ..." "$cnice"
        mkdir $dst/$c
        bash copy-runner copiers.d/$c.cp $src $dst/$c \
            && echo " ok" \
            || echo " FAIL"
    done
}

case $1 in
    create-all|create-vol|clean-all)
        $1 $2
    ;;
    verify-all|compare-all|copy-all)
        $1 $2 $3 $4
    ;;
    *)
        echo "Ops: "
        echo "   create-vol, create-all, verify-all, "
        echo "   compare-all, clean-all, copy-all"
        exit 1
    ;;
esac
