#!/bin/bash

if [ ! "`id -u`" = 0 ]; then
    echo "Copying as a non-root user is not advised."
fi

copier=$1
src=$2
dst=$3

source $copier

uname -a > $dst/meta
echo $copier >> $dst/meta
version >> $dst/meta
backup $src $dst &> $dst/log
