#!/bin/bash

source $1
shift

case $1 in
    create)
        $1 $2
    ;;
    clean)
        cd $2
        clean
    ;;
    compare|verify)
        $1 $2 $3
    ;;
    *)
        echo "Ops: create, verify, clean, compare"
        exit 1
    ;;
esac
