#!/bin/bash

declare -a priority_desc
priority_desc=([$Critical]='(Critical)' \
    [$Important]='(Important)' \
    [$Exhaustive]='')

has_subtests=""

begin-subtests () {
    [ -n "$DETAIL" ] && echo
}

subtest () {
    if [ -n "$DETAIL" ]; then
        has_subtests="1"
        test_desc="${priority_desc[$test_priority]}"
        printf "   Sub-test: %${printWidth}s ... " "$1"
        if [ "$2" = "0" ]; then
            echo "ok $test_desc"
        else
            echo "FAIL $test_desc"
        fi
    fi
}

alltrue () {
    while [ -n "$1" ]; do
        [ "$1" = "0" ] || return 1
        shift
    done
    return 0
}

source $1
shift

case $1 in
    create)
        $1 $2
    ;;
    clean)
        cd $2
        clean
    ;;
    compare|verify)
        activity=$2
        testname=$3
        src=$4
        dst=$5

        max_priority=`max_priority`
        test_priority=$max_priority
        max_desc=${priority_desc[$max_priority]}
        if (( $max_priority <= $run_priority )); then
            printf "%s: %${printWidth}s ... " "$activity" "$testname"
            $1 $src $dst
            x=$?
            # Only print the final status if there weren't subtests
            if [ ! "$has_subtests" ]; then
                if [ "$x" = "0" ]; then
                    echo "ok $max_desc"
                else
                    echo "FAIL $max_desc"
                fi
            fi
        fi
    ;;
    *)
        echo "Ops: create, verify, clean, compare"
        exit 1
    ;;
esac
